#!/bin/bash
set -e
if [ -z $LAWPATH ]; then
    echo "The LAWPATH environment variable must be set for the environment script to work."
    echo "Please set 'export MMPATH=<path to march-madness repo>' before continuing"
    exit 1
fi
echo "-> Using LAWPATH=$LAWPATH"
cd $LAWPATH/env
if [ ! -d "core" ]; then
    python -m venv core 
fi
source core/bin/activate
pip install -r deps.txt
cd $LAWPATH/src
pip install .
cd ..
deactivate
echo "-> Done"
